Рассмотрим такие статистические термины, как категориальные и числовые признаки.

Под числовыми признаками обычно подразумевают признаки, которые отражают количественную меру и могут принимать значения из неограниченного диапазона.

Числовые признаки могут быть:
- дискретными (например, количество комнат, пациентов, дней);
- непрерывными (например, масса, цена, площадь).
- Дискретные признаки чаще всего представлены целыми числами, а непрерывные — целыми числами и числами с плавающей точкой.

Под категориальными признаками обычно подразумевают столбцы в таблице, которые обозначают принадлежность объекта к какому-то классу/категории.

Категориальные признаки могут быть:
- номинальными (например, пол, национальность, район);
- порядковыми (например, уровень образования, уровень комфорта, стадия заболевания).
- Такие признаки имеют ограниченный набор значений. Они чаще всего представлены в виде текстового описания и кодируются в Pandas типом данных object.

## Категории в данных о недвижимости

Давайте определим число уникальных категорий в каждом столбце нашей таблицы melb_df. Для этого создадим вспомогательную таблицу unique_counts:

In [2]:
import pandas as pd 

melb_df = pd.read_csv('data/melb_data_ps.csv')

# display(melb_df.head())
# создаём пустой список
unique_list = []
# проегаемся по именам столбцов
for col in melb_df.columns:
    # создаём кортеж (имя столбца, число уникальных значений)
    item = (col, melb_df[col].nunique(), melb_df[col].dtype) # добавляем кортеж в список
    unique_list.append(item)

# создаём вспомогательную таблицу и сортируем её
unique_counts = pd.DataFrame(unique_list, columns=['Column_Name', 'Num_unique', 'Type']).sort_values(by='Num_unique', ignore_index=True)
display(unique_counts)

      Column_Name  Num_unique     Type
0            Type           3      str
1          Method           5      str
2      Regionname           8      str
3           Rooms           9    int64
4        Bathroom           9    int64
5             Car          11    int64
6         Bedroom          12    int64
7     CouncilArea          33      str
8            Date          58      str
9       YearBuilt         144    int64
10       Postcode         198    int64
11       Distance         202  float64
12        SellerG         268      str
13  Propertycount         311    int64
14         Suburb         314      str
15   BuildingArea         602  float64
16       Landsize        1448  float64
17          Price        2204  float64
18      Lattitude        6503  float64
19     Longtitude        7063  float64
20    Coordinates       13097      str
21        Address       13378      str
22          index       13580    int64

### Самый простой способ преобразования столбцов к типу данных category — это использование уже знакомого нам метода astype(), в параметры которого достаточно передать строку 'category'.

Рассмотрим это на примере.

Для начала, выведем информацию о памяти, занимаемой текущей таблицей, с помощью метода info():

In [3]:
display(melb_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  str
 2   Address        13580 non-null  str
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  str
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  str
 7   SellerG        13580 non-null  str
 8   Date           13580 non-null  str
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  str
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  str
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  str
dtypes: float64(6), int64(8), str(9)
memory usage: 2.4 MB

None

Сделаем преобразование столбцов к типу данных category:

In [ ]:
col_to_exclude = ['Date', 'Rooms', 'Room', 'Bathroom','Car']
max_unique_count = 150
for col in melb_df.columns: # цикл по именам столбцов
    if melb_df[col].nunique() < max_unique_count and col not in col_to_exclude:  # проверяем условие
        melb_df[col] = melb_df[col].astype('category') # преобразуем тип столбца
        
display(melb_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  str
 2   Address        13580 non-null  str
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  category
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  category
 7   SellerG        13580 non-null  str
 8   Date           13580 non-null  str
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  category
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  category
 17  CouncilArea    12211 non-null  category
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  category
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  str
dtypes: category(6), float64(6), int64(6), str(5)
memory usage: 1.9 MB

None

Особенно хорошо такое преобразование работает на действительно больших данных, где число строк превышает сотни тысяч или миллионы. Иногда изменение типов может уменьшить объём памяти в десятки раз и существенно увеличить производительность.

## Получение атрибутов category

У типа данных category есть свой специальный аксесcор cat, который позволяет получать информацию о своих значениях и преобразовывать их. Например, с помощью атрибута этого аксессора categories мы можем получить список уникальных категорий в столбце Regionname:

In [6]:
print(melb_df['Regionname'].cat.categories)

Index(['Eastern Metropolitan', 'Eastern Victoria', 'Northern Metropolitan',
       'Northern Victoria', 'South-Eastern Metropolitan',
       'Southern Metropolitan', 'Western Metropolitan', 'Western Victoria'],
      dtype='str')

А теперь посмотрим, каким образом столбец кодируется в виде чисел в памяти компьютера. Для этого можно воспользоваться атрибутом codes:

In [7]:
display(melb_df['Regionname'].cat.codes)

0        2
1        2
2        2
3        2
4        2
        ..
13575    4
13576    6
13577    6
13578    6
13579    6
Length: 13580, dtype: int8

С помощью метода аксессора rename_categories() можно легко переименовать текущие значения категорий. Для этого в данный метод нужно передать словарь, ключи которого — старые имена категорий, а значения — новые.

Рассмотрим на примере: переименуем категории признака типа постройки Type — заменим их на полные названия (напомним, u — unit, h — house, t — townhouse).

In [14]:
melb_df['Type'] = melb_df['Type'].cat.rename_categories({'h':'house', 'Unit': 'unit', 't': 'townhouse'})
display(melb_df['Type'])

0        house
1        house
2        house
3        house
4        house
         ...
13575    house
13576    house
13577    house
13578    house
13579    house
Name: Type, Length: 13580, dtype: category
Categories (3, str): ['house', 'townhouse', 'unit']

## Подводные камни

А теперь представим ситуацию, что появилась новая партия домов и теперь мы продаём и квартиры (flat). Создадим объект Series new_houses_types, в котором будем хранить типы зданий новой партии домов. Преобразуем тип new_houses_types в такой же тип, как и у столбца Type в таблице melb_data, и выведем результат на экран:

In [15]:
new_house_type = pd.Series(['unit', 'house', 'flat', 'flat', 'house'])
new_house_type = new_house_type.astype(melb_df['Type'].dtype)
display(new_house_type)

C:\Users\user\AppData\Local\Temp\ipykernel_28480\3155728388.py:2: Pandas4Warning: Constructing a Categorical with a dtype and values containing non-null entries not in that dtype's categories is deprecated and will raise in a future version.
  new_house_type = new_house_type.astype(melb_df['Type'].dtype)

0     unit
1    house
2      NaN
3      NaN
4    house
dtype: category
Categories (3, str): ['house', 'townhouse', 'unit']

Примечание. Добавление новой категории в столбец Type не отразится на самом столбце — текущие категории не изменятся, однако такое преобразование позволит добавлять в таблицу новые данные о домах с новой категорией — flat.

In [19]:
new_house_type = new_house_type.cat.rename_categories({'NaN': 'flat'})# попробова заменить Nan на flat, но не получилось, так как в серии нет категории NaN
display(new_house_type)

0     unit
1    house
2      NaN
3      NaN
4    house
dtype: category
Categories (3, str): ['house', 'townhouse', 'unit']

Примечание. Добавление новой категории в столбец Type не отразится на самом столбце — текущие категории не изменятся, однако такое преобразование позволит добавлять в таблицу новые данные о домах с новой категорией — flat.

Из данного примера можно сделать вывод, что если набор категорий в столбце жёстко не зафиксирован и может обновляться в процессе работы, то тип category не является подходящим типом данных для этого столбца или необходимо постоянно писать проверки при обновлении таблицы.

Теперь, когда мы рассмотрели основные моменты и нюансы работы с типом данных category, можно сформулировать несколько рекомендаций по его использованию:

1. Необязательно каждый раз преобразовывать категориальные данные в тип данных category. Зачастую это делается исключительно для оптимизации работы с большими данными.

2. Если набор данных занимает значительный процент используемой оперативной памяти, рассмотрите возможность использования типа category.

3. Если у вас очень серьёзные проблемы с производительностью, обратите внимание на использование типа category.

4. Если вы решили использовать тип category, будьте осторожны при добавлении новой информации в вашу таблицу. Убедитесь, что вы собрали всю необходимую информацию, произведите предобработку данных и только после этого используйте преобразование типов.

Задание 5.2

При преобразовании столбцов таблицы о недвижимости к типу category мы оставили без внимания столбец Suburb (пригород). Давайте исправим это.

- С помощью метода info() узнайте, сколько памяти занимает таблица melb_df.

- Преобразуйте признак Suburb следующим образом: оставьте в столбце только 119 наиболее популярных пригородов, остальные замените на 'other'.
- Приведите данные в столбце Suburb к категориальному типу.

В качестве ответа запишите разницу между объёмом занимаемой памяти до преобразования (который мы получили ранее в модуле) и после него в Мб. Ответ округлите до десятых.

In [44]:


max_unique_count = 119
for suburb in melb_df['Suburb'].unique(): # цикл по именам столбцов
    if melb_df['Suburb'].nunique() < max_unique_count: # проверяем условие
        melb_df['Suburb'] = melb_df['Suburb'].astype('category') # преобразуем тип столбца
    else:
        melb_df['Suburb'] = melb_df['Suburb'].astype('other') # преобразуем тип столбца
print(melb_df['Suburb'].cat.categories)
display(melb_df.info())

Index(['Ascot Vale', 'Balwyn North', 'Bentleigh', 'Bentleigh East', 'Brighton',
       'Brighton East', 'Brunswick', 'Camberwell', 'Carnegie', 'Coburg',
       'Elwood', 'Essendon', 'Footscray', 'Glen Iris', 'Glenroy', 'Hampton',
       'Hawthorn', 'Hawthorn East', 'Keilor East', 'Kew', 'Moonee Ponds',
       'Newport', 'Northcote', 'Pascoe Vale', 'Port Melbourne', 'Prahran',
       'Preston', 'Reservoir', 'Richmond', 'South Yarra', 'St Kilda',
       'Surrey Hills', 'Thornbury', 'Yarraville', 'other'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  category
 2   Address        13580 non-null  str
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  category
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  category
 7   SellerG        13580 non-null  str
 8   Date           13580 non-null  str
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  category
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  category
 17  CouncilArea    12211 non-null  category
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  category
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  str
dtypes: category(7), float64(6), int64(6), str(4)
memory usage: 1.8 MB

None

Вашим заданием в этом модуле будет проанализировать и преобразовать данные о велопоездках клиентов компании Citi Bike (США), специализирующейся на прокате велосипедов.

Датасет представляет собой таблицу с информацией о 300 тысячах поездок за первые пять дней сентября 2018 года и включает в себя следующую информацию:

- starttime — время начала поездки (дата, время);
- stoptime — время окончания поездки (дата, время);
- start station id — идентификатор стартовой стоянки;
- start station name — название стартовой стоянки;
- start station latitude, start station longitude — географическая широта и долгота стартовой стоянки;
- end station id — идентификатор конечной стоянки;
- end station name — название конечной стоянки;
- end station latitude, end station longitude — географическая широта и долгота конечной стоянки;
- bikeid — идентификатор велосипеда;
- usertype — тип пользователя (Customer — клиент с подпиской на 24 часа или на три дня, Subscriber — подписчик с годовой арендой велосипеда);
- birth year — год рождения клиента;
- gender — пол клиента (0 — неизвестный, 1 — мужчина, 2 — женщина).

In [ ]:
import pandas as pd
bike_data = pd.read_csv('data/citibike-tripdata.csv', sep=',')

bike_df = bike_data.copy()

display(bike_df.head(10))

,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2018-09-01 00:00:05.2690,2018-09-01 00:27:20.6340,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1980,1
1,2018-09-01 00:00:11.2810,2018-09-01 00:02:23.4810,314.0,Cadman Plaza West & Montague St,40.693830,-73.990539,3242.0,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,1969,0
2,2018-09-01 00:00:20.6490,2018-09-01 00:55:58.5470,3142.0,1 Ave & E 62 St,40.761227,-73.960940,3384.0,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1975,1
3,2018-09-01 00:00:21.7460,2018-09-01 00:07:38.5830,308.0,St James Pl & Oliver St,40.713079,-73.998512,3690.0,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,1984,2
4,2018-09-01 00:00:27.3150,2018-09-01 02:21:25.3080,345.0,W 13 St & 6 Ave,40.736494,-73.997044,380.0,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1994,1
5,2018-09-01 00:00:29.3030,2018-09-01 00:55:56.2020,3142.0,1 Ave & E 62 St,40.761227,-73.960940,3384.0,Smith St & 3 St,40.678724,-73.995991,21693,Subscriber,1977,2
6,2018-09-01 00:00:27.2780,2018-09-01 00:04:20.7420,3526.0,31 St & 23 Ave,40.774788,-73.912555,3532.0,Ditmars Blvd & 19 St,40.781450,-73.918330,29789,Subscriber,1989,1
7,2018-09-01 00:00:31.4250,2018-09-01 00:05:17.4110,358.0,Christopher St & Greenwich St,40.732916,-74.007114,405.0,Washington St & Gansevoort St,40.739323,-74.008119,32861,Subscriber,1991,1
8,2018-09-01 00:00:30.9660,2018-09-01 00:19:18.4710,285.0,Broadway & E 14 St,40.734546,-73.990741,405.0,Washington St & Gansevoort St,40.739323,-74.008119,25039,Subscriber,1982,1
9,2018-09-01 00:00:42.1670,2018-09-01 00:07:45.6770,319.0,Fulton St & Broadway,40.711066,-74.009447,426.0,West St & Chambers St,40.717548,-74.013221,20508,Subscriber,1974,2

Итак, начнём с разминки и произведём базовый анализ, чтобы познакомиться с данными поближе, а заодно повторим темы предыдущего модуля.

In [63]:
# Сколько пропусков в столбце start station id?
print(bike_df['start station id'].isna().sum())
# Какой тип данных имеют столбцы starttime и stoptime?
#print(bike_df.info())

# Найдите идентификатор самой популярной стартовой стоянки. Запишите идентификатор в виде целого числа.
#print(bike_df['start station id'].value_counts())
# Велосипед с каким идентификатором является самым популярным?
print(bike_df['bikeid'].value_counts())
# Какой тип клиентов (столбец usertype) является преобладающим — Subscriber или Customer? В качестве ответа запишите долю клиентов преобладающего типа среди общего количества клиентов. Ответ округлите до сотых.
print(round(bike_df['usertype'].value_counts(normalize=True)['Subscriber'], 2))
# Кто больше занимается велоспортом — мужчины или женщины? В ответ запишите число поездок для той группы, у которой их больше.
print(bike_df['gender'].value_counts())
# число стоянок 
print(bike_df['start station id'].nunique()) 
print(bike_df['end station id'].nunique())

169
bikeid
33887    107
34358    104
34258    103
34159    103
34730    102
        ...
18083      1
17567      1
15122      1
15681      1
25794      1
Name: count, Length: 10004, dtype: int64
0.77
gender
1    183582
2     74506
0     41912
Name: count, dtype: int64
759
765

In [70]:
#  В рассматриваемые дни минимальный возраст клиента составлял 10 лет
print((2026 - bike_df['birth year'].max()))
# Самой непопулярной стартовой стоянкой из тех, которыми воспользовались клиенты, является стоянка с названием "Eastern Pkwy & Washington Ave"
# print(bike_df['start station name'].value_counts())
# Наибольшее количество поездок завершается на стоянке под названием "Liberty Light Rail"
print(bike_df['end station name'].value_counts())

24
end station name
West St & Chambers St          1963
12 Ave & W 40 St               1909
Pershing Square North          1850
Central Park S & 6 Ave         1828
E 17 St & Broadway             1804
                               ...
Exchange Place                    3
Union St                          1
Warren St                         1
Montrose Ave & Bushwick Ave       1
Liberty Light Rail                1
Name: count, Length: 765, dtype: int64

## Задание 6.8

В первую очередь удалим лишнюю информацию из данных.

В наших данных присутствуют столбцы, которые дублируют информацию друг о друге: это столбцы с идентификатором и названием стартовой и конечной стоянки. Удалите признаки идентификаторов стоянок. Сколько столбцов осталось?

In [81]:
display(bike_df.shape)

(300000, 10)

Замените признак birth year на более понятный признак возраста клиента age. Годом отсчёта возраста выберите 2018 год. Столбец birth year удалите из таблицы. Сколько поездок совершено клиентами старше 60 лет?

In [92]:
display(bike_df['age'].value_counts())
ages = 0
for col in bike_df['age']:
    if col > 60:
        ages += 1
print(ages)

age
49     43959
30     12551
28     12051
29     11704
27     11640
       ...
109        1
103        1
129        1
82         1
111        1
Name: count, Length: 91, dtype: int64

11837

Создайте признак длительности поездки trip duration. Для этого вычислите интервал времени между временем окончания поездки (stoptime) и её началом (starttime). Сколько целых минут длилась поездка под индексом 3 в таблице?

In [105]:
display(bike_data.head())

bike_df['trip dauration'] = bike_df['stoptime'].dt.minute - bike_df['starttime'].dt.minute
display(bike_df.head())

,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2018-09-01 00:00:05.2690,2018-09-01 00:27:20.6340,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1980,1
1,2018-09-01 00:00:11.2810,2018-09-01 00:02:23.4810,314.0,Cadman Plaza West & Montague St,40.693830,-73.990539,3242.0,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,1969,0
2,2018-09-01 00:00:20.6490,2018-09-01 00:55:58.5470,3142.0,1 Ave & E 62 St,40.761227,-73.960940,3384.0,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1975,1
3,2018-09-01 00:00:21.7460,2018-09-01 00:07:38.5830,308.0,St James Pl & Oliver St,40.713079,-73.998512,3690.0,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,1984,2
4,2018-09-01 00:00:27.3150,2018-09-01 02:21:25.3080,345.0,W 13 St & 6 Ave,40.736494,-73.997044,380.0,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1994,1

,starttime,stoptime,start station latitude,start station longitude,end station latitude,end station longitude,bikeid,usertype,gender,age,trip dauration
0,2018-09-01 00:00:05.269,2018-09-01 00:00:05.269,40.732264,-73.998522,40.693261,-73.968896,25577,Subscriber,1,38,0
1,2018-09-01 00:00:11.281,2018-09-01 00:00:11.281,40.693830,-73.990539,40.691029,-73.991834,34377,Subscriber,0,49,0
2,2018-09-01 00:00:20.649,2018-09-01 00:00:20.649,40.761227,-73.960940,40.678724,-73.995991,30496,Subscriber,1,43,0
3,2018-09-01 00:00:21.746,2018-09-01 00:00:21.746,40.713079,-73.998512,40.713342,-74.009355,28866,Subscriber,2,34,0
4,2018-09-01 00:00:27.315,2018-09-01 00:00:27.315,40.736494,-73.997044,40.734011,-74.002939,20943,Customer,1,24,0