In [1]:
import pandas as pd
import numpy as np

data = {
    'employee_id': range(1, 41),

    'name': [
        'Alex', 'John', 'Anna', 'Mike', 'Sara',
        'Tom', 'Kate', 'Bob', 'Lisa', 'David'
    ] * 4,

    'department': [
        'IT', 'HR', 'Finance', 'IT', 'Marketing',
        'Finance', 'HR', 'IT', 'Marketing', 'Finance'
    ] * 4,

    'city': [
        'Moscow', 'SPB', 'Kazan', 'Moscow', 'SPB',
        'Kazan', 'Moscow', 'SPB', 'Kazan', 'Moscow'
    ] * 4,

    'salary': [
        120000, 80000, 95000, 110000, 70000,
        99000, 85000, 130000, 72000, 105000
    ] * 4,

    'age': [
        25, 32, 29, 41, 24,
        36, 28, 45, 27, 38
    ] * 4,

    'experience_years': [
        1, 5, 3, 10, 1,
        7, 2, 15, 2, 8
    ] * 4,

    'bonus_percent': [
        10, 15, np.nan, 20, 5,
        12, 8, 25, np.nan, 18
    ] * 4,

    'performance_score': [
        'A', 'B', 'A', 'A', 'C',
        'B', 'B', 'A', 'C', 'B'
    ] * 4,

    'employment_date': pd.date_range(
        start='2021-01-10',
        periods=40,
        freq='MS'
    ).astype(str),

    'remote': [
        'Yes', 'No', 'Yes', 'Yes', 'No',
        'No', 'Yes', 'No', 'Yes', 'No'
    ] * 4
}

df = pd.DataFrame(data)

# Добавим пропуски
df.loc[5, 'salary'] = np.nan
df.loc[12, 'city'] = np.nan
df.loc[20, 'age'] = np.nan

# Сохраняем CSV
df.to_csv('employees.csv', index=False)

print(df.head())

   employee_id  name department    city    salary   age  experience_years  \
0            1  Alex         IT  Moscow  120000.0  25.0                 1
1            2  John         HR     SPB   80000.0  32.0                 5
2            3  Anna    Finance   Kazan   95000.0  29.0                 3
3            4  Mike         IT  Moscow  110000.0  41.0                10
4            5  Sara  Marketing     SPB   70000.0  24.0                 1

   bonus_percent performance_score employment_date remote
0           10.0                 A      2021-02-01    Yes
1           15.0                 B      2021-03-01     No
2            NaN                 A      2021-04-01    Yes
3           20.0                 A      2021-05-01    Yes
4            5.0                 C      2021-06-01     No

Структура обучения
- Уровень 1 — база
- Уровень 2 — фильтрация и сортировка
- Уровень 3 — очистка и преобразование
- Уровень 4 — даты и категории
- Уровень 5 — groupby и агрегации
- Уровень 6 — мини-проект
- Решения

## УРОВЕНЬ 1 — БАЗА
Задание 1
Условие

Загрузи CSV-файл employees.csv в DataFrame.

Использовать
pd.read_csv()

Ожидаемый результат

Переменная df содержит таблицу.

Подсказка

Путь к файлу — строка.

In [2]:
employees_data = pd.read_csv('employees.csv', sep=',')
em_df = employees_data.copy()

Задание 2

Условие

Выведи первые 5 строк таблицы.

Использовать
head()
Ожидаемый результат

Первые записи DataFrame.

Подсказка

Метод вызывается у DataFrame.

In [3]:
em_df.head()

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote
0,1,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-02-01,Yes
1,2,John,HR,SPB,80000.0,32.0,5,15.0,B,2021-03-01,No
2,3,Anna,Finance,Kazan,95000.0,29.0,3,NaN,A,2021-04-01,Yes
3,4,Mike,IT,Moscow,110000.0,41.0,10,20.0,A,2021-05-01,Yes
4,5,Sara,Marketing,SPB,70000.0,24.0,1,5.0,C,2021-06-01,No

Задание 3

Условие

Посмотри:

количество строк и столбцов;
типы данных;
общую информацию о таблице.
Использовать
shape
dtypes
info()
Ожидаемый результат

Понимание структуры данных.

Подсказка

shape — это атрибут, а не метод.

In [4]:
em_df.info()
em_df.shape[0]

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        40 non-null     int64
 1   name               40 non-null     str
 2   department         40 non-null     str
 3   city               39 non-null     str
 4   salary             39 non-null     float64
 5   age                39 non-null     float64
 6   experience_years   40 non-null     int64
 7   bonus_percent      32 non-null     float64
 8   performance_score  40 non-null     str
 9   employment_date    40 non-null     str
 10  remote             40 non-null     str
dtypes: float64(3), int64(2), str(6)
memory usage: 3.6 KB

40

Задание 4
Условие

Выведи статистику по числовым столбцам.

Использовать
describe()
Ожидаемый результат

Среднее, минимум, максимум и др.

Подсказка

Метод автоматически берёт numeric columns.

In [5]:
em_df.describe()

       employee_id         salary        age  experience_years  bonus_percent
count    40.000000      39.000000  39.000000         40.000000      32.000000
mean     20.500000   96538.461538  32.692308          5.400000      14.125000
std      11.690452   19582.277371   6.867750          4.419073       6.333475
min       1.000000   70000.000000  24.000000          1.000000       5.000000
25%      10.750000   80000.000000  27.000000          2.000000       9.500000
50%      20.500000   95000.000000  32.000000          4.000000      13.500000
75%      30.250000  110000.000000  38.000000          8.000000      18.500000
max      40.000000  130000.000000  45.000000         15.000000      25.000000

Задание 5
Условие

Выведи отдельно:

столбец salary;
столбцы name и department.
Использовать
выбор столбцов
Ожидаемый результат

Series и DataFrame.

Подсказка

Для нескольких столбцов нужны двойные скобки.

In [6]:
em_df[['name','salary','department']].head()

   name    salary department
0  Alex  120000.0         IT
1  John   80000.0         HR
2  Anna   95000.0    Finance
3  Mike  110000.0         IT
4  Sara   70000.0  Marketing

Задание 6
Условие

Выведи:

- первую строку;
- строки с 5 по 10;
- последние 3 строки.
- Использовать
- iloc
- tail()
Ожидаемый результат

Навык индексации строк.

Подсказка

iloc работает по индексам.

In [7]:
display(em_df.iloc[1])

employee_id                   2
name                       John
department                   HR
city                        SPB
salary                  80000.0
age                        32.0
experience_years              5
bonus_percent              15.0
performance_score             B
employment_date      2021-03-01
remote                       No
Name: 1, dtype: object

In [8]:
em_df.iloc[5:11]

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote
5,6,Tom,Finance,Kazan,NaN,36.0,7,12.0,B,2021-07-01,No
6,7,Kate,HR,Moscow,85000.0,28.0,2,8.0,B,2021-08-01,Yes
7,8,Bob,IT,SPB,130000.0,45.0,15,25.0,A,2021-09-01,No
8,9,Lisa,Marketing,Kazan,72000.0,27.0,2,NaN,C,2021-10-01,Yes
9,10,David,Finance,Moscow,105000.0,38.0,8,18.0,B,2021-11-01,No
10,11,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-12-01,Yes

In [9]:
em_df.tail(3)

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote
37,38,Bob,IT,SPB,130000.0,45.0,15,25.0,A,2024-03-01,No
38,39,Lisa,Marketing,Kazan,72000.0,27.0,2,NaN,C,2024-04-01,Yes
39,40,David,Finance,Moscow,105000.0,38.0,8,18.0,B,2024-05-01,No

## УРОВЕНЬ 2 — ФИЛЬТРАЦИЯ И СОРТИРОВКА

Задание 1
Условие

Найди всех сотрудников старше 35 лет.

Использовать
фильтрацию
Ожидаемый результат

Только нужные строки.

Подсказка

Условие пишется в квадратных скобках.

In [10]:
age = em_df[em_df['age'] > 35]
age.head()

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote
3,4,Mike,IT,Moscow,110000.0,41.0,10,20.0,A,2021-05-01,Yes
5,6,Tom,Finance,Kazan,NaN,36.0,7,12.0,B,2021-07-01,No
7,8,Bob,IT,SPB,130000.0,45.0,15,25.0,A,2021-09-01,No
9,10,David,Finance,Moscow,105000.0,38.0,8,18.0,B,2021-11-01,No
13,14,Mike,IT,Moscow,110000.0,41.0,10,20.0,A,2022-03-01,Yes

Задание 2
Условие

Найди сотрудников:

- из отдела IT;
- с зарплатой выше 115000.
- Использовать &

Ожидаемый результат

Комбинированная фильтрация.

Подсказка

Каждое условие — в круглых скобках.

In [11]:
department_salary = em_df[(em_df['department'] == 'IT') & (em_df['salary'] > 115000)]
department_salary.head()

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote
0,1,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-02-01,Yes
7,8,Bob,IT,SPB,130000.0,45.0,15,25.0,A,2021-09-01,No
10,11,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-12-01,Yes
17,18,Bob,IT,SPB,130000.0,45.0,15,25.0,A,2022-07-01,No
20,21,Alex,IT,Moscow,120000.0,NaN,1,10.0,A,2022-10-01,Yes

Задание 3
Условие

Найди сотрудников:

- из Moscow ИЛИ SPB.
- Использовать | isin()

Ожидаемый результат

Фильтрация по нескольким значениям.

Подсказка

isin() часто удобнее.

In [12]:
city = em_df[em_df['city'].isin(['Moscow','SPB'])]
city.head()

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote
0,1,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-02-01,Yes
1,2,John,HR,SPB,80000.0,32.0,5,15.0,B,2021-03-01,No
3,4,Mike,IT,Moscow,110000.0,41.0,10,20.0,A,2021-05-01,Yes
4,5,Sara,Marketing,SPB,70000.0,24.0,1,5.0,C,2021-06-01,No
6,7,Kate,HR,Moscow,85000.0,28.0,2,8.0,B,2021-08-01,Yes

Задание 4
Условие

Отсортируй сотрудников:

- по зарплате по убыванию;
- затем по возрасту по возрастанию.
- Использовать
- sort_values()

Ожидаемый результат

Мультисортировка.

Подсказка

Передай список столбцов.

In [13]:
sorted_df = em_df.sort_values(by=['salary', 'age'], ascending=[False, True])
sorted_df.head()

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote
7,8,Bob,IT,SPB,130000.0,45.0,15,25.0,A,2021-09-01,No
17,18,Bob,IT,SPB,130000.0,45.0,15,25.0,A,2022-07-01,No
27,28,Bob,IT,SPB,130000.0,45.0,15,25.0,A,2023-05-01,No
37,38,Bob,IT,SPB,130000.0,45.0,15,25.0,A,2024-03-01,No
0,1,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-02-01,Yes

Задание 5
Условие

Посчитай:

- сколько сотрудников в каждом отделе;
- сколько сотрудников работают удалённо.

Использовать
- value_counts()

Ожидаемый результат

Частоты значений.

Подсказка

Метод вызывается у Series.

In [14]:
department_counts = em_df['department'].value_counts()
remote_counts = em_df['remote'].value_counts()  
remote_counts

remote
Yes    20
No     20
Name: count, dtype: int64

Задание 6
Условие

- Выведи топ-5 самых высоких зарплат.

Использовать
- sort_values()
- head()
Ожидаемый результат

5 строк с максимальными salary.ч

Подсказка

Сортировка должна быть descending.

In [15]:
em_df.sort_values(by='salary', ascending=False).head(5)

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote
7,8,Bob,IT,SPB,130000.0,45.0,15,25.0,A,2021-09-01,No
27,28,Bob,IT,SPB,130000.0,45.0,15,25.0,A,2023-05-01,No
17,18,Bob,IT,SPB,130000.0,45.0,15,25.0,A,2022-07-01,No
37,38,Bob,IT,SPB,130000.0,45.0,15,25.0,A,2024-03-01,No
10,11,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-12-01,Yes

## УРОВЕНЬ 3 — ОЧИСТКА И ПРЕОБРАЗОВАНИЕ

Задание 1
Условие

Проверь:

- сколько пропусков в каждом столбце.
-  Использовать
- isnull()
- sum()
Ожидаемый результат

Количество NaN.

Подсказка

True считается как 1.

In [16]:
em_df.isnull().sum()

employee_id          0
name                 0
department           0
city                 1
salary               1
age                  1
experience_years     0
bonus_percent        8
performance_score    0
employment_date      0
remote               0
dtype: int64

Задание 2
Условие

Замени пропуски в salary на среднюю зарплату.

Использовать
- fillna()
- mean()
Ожидаемый результат

В salary больше нет NaN.

Подсказка

Среднее можно сохранить в переменную.

In [17]:
em_df['salary'].fillna(em_df['salary'].mean(), inplace=True)
em_df.head()

C:\Users\Luka\AppData\Local\Temp\ipykernel_19936\3699613890.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  em_df['salary'].fillna(em_df['salary'].mean(), inplace=True)

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote
0,1,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-02-01,Yes
1,2,John,HR,SPB,80000.0,32.0,5,15.0,B,2021-03-01,No
2,3,Anna,Finance,Kazan,95000.0,29.0,3,NaN,A,2021-04-01,Yes
3,4,Mike,IT,Moscow,110000.0,41.0,10,20.0,A,2021-05-01,Yes
4,5,Sara,Marketing,SPB,70000.0,24.0,1,5.0,C,2021-06-01,No

Задание 3
Условие

Удалить строки, где отсутствует city.

Использовать
- dropna()
Ожидаемый результат

Строки с NaN в city удалены.

Подсказка

Используй параметр subset.

In [18]:
em_df.dropna(subset=['city'], inplace=True)

Задание 4
Условие

Создай новый столбец:
- salary_with_bonus

Формула:
```
salary + salary * bonus_percent / 100
```

Использовать
создание столбцов

Ожидаемый результат

Новый numeric column.

Подсказка

Операции можно делать прямо между Series.

In [19]:
em_df['slary_with_bonus'] = em_df['salary'] + em_df['salary'] * (em_df['bonus_percent'] / 100)
em_df.head()

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote,slary_with_bonus
0,1,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-02-01,Yes,132000.0
1,2,John,HR,SPB,80000.0,32.0,5,15.0,B,2021-03-01,No,92000.0
2,3,Anna,Finance,Kazan,95000.0,29.0,3,NaN,A,2021-04-01,Yes,NaN
3,4,Mike,IT,Moscow,110000.0,41.0,10,20.0,A,2021-05-01,Yes,132000.0
4,5,Sara,Marketing,SPB,70000.0,24.0,1,5.0,C,2021-06-01,No,73500.0

Задание 5
Условие

Создай столбец:
- salary_level

Правила:
```
< 90000 → Low
90000–110000 → Middle

110000 → High

Использовать
apply()
```

Ожидаемый результат

Категории зарплат.

Подсказка

Сделай отдельную функцию.

In [20]:
def slary_level_function(salary):
    if salary < 90000:
        return 'Low'
    elif 90000 <= salary < 110000:
        return 'Medium'
    else:
        return 'High'
    
em_df['salary_level'] = em_df['salary'].apply(slary_level_function)
em_df.head()

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote,slary_with_bonus,salary_level
0,1,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-02-01,Yes,132000.0,High
1,2,John,HR,SPB,80000.0,32.0,5,15.0,B,2021-03-01,No,92000.0,Low
2,3,Anna,Finance,Kazan,95000.0,29.0,3,NaN,A,2021-04-01,Yes,NaN,Medium
3,4,Mike,IT,Moscow,110000.0,41.0,10,20.0,A,2021-05-01,Yes,132000.0,High
4,5,Sara,Marketing,SPB,70000.0,24.0,1,5.0,C,2021-06-01,No,73500.0,Low

Задание 6
Условие

Замени значения:

- Yes → 1
- No → 0

в столбце remote.

Использовать
replace()

Ожидаемый результат

Числовой столбец.

Подсказка

Передай словарь.

In [32]:
em_df.replace({'remote': {'Yes': 1, 'No': 0}}, inplace=True)
em_df.head()

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote,slary_with_bonus,salary_level
0,1,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-02-01,1,132000.0,High
1,2,John,HR,SPB,80000.0,32.0,5,15.0,B,2021-03-01,0,92000.0,Low
2,3,Anna,Finance,Kazan,95000.0,29.0,3,NaN,A,2021-04-01,1,NaN,Medium
3,4,Mike,IT,Moscow,110000.0,41.0,10,20.0,A,2021-05-01,1,132000.0,High
4,5,Sara,Marketing,SPB,70000.0,24.0,1,5.0,C,2021-06-01,0,73500.0,Low

Задание 7
Условие

Преобразуй:

- remote → int
- salary → int

Использовать
- astype()

Ожидаемый результат

Изменённые типы данных.

Подсказка

Сначала убери NaN.

In [44]:
em_df['remote'].astype(int)
em_df.replace({'salary': {np.nan: 0}}, inplace=True)
em_df['salary'].astype(int)

em_df.head()

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote,slary_with_bonus,salary_level
0,1,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-02-01,1,132000.0,High
1,2,John,HR,SPB,80000.0,32.0,5,15.0,B,2021-03-01,0,92000.0,Low
2,3,Anna,Finance,Kazan,95000.0,29.0,3,NaN,A,2021-04-01,1,NaN,Medium
3,4,Mike,IT,Moscow,110000.0,41.0,10,20.0,A,2021-05-01,1,132000.0,High
4,5,Sara,Marketing,SPB,70000.0,24.0,1,5.0,C,2021-06-01,0,73500.0,Low

## УРОВЕНЬ 4 — ДАТЫ И КАТЕГОРИИ

Задание 1
Условие

Преобразуй employment_date в datetime.

Использовать
- pd.to_datetime()
Ожидаемый результат

Тип datetime64.

Подсказка

Проверь через dtypes.

In [70]:
pd.to_datetime(em_df['employment_date'])
em_df.head()

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote,slary_with_bonus,salary_level,hire_year,hire_month,hire_of_week
0,1,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-02-01,1,132000.0,High,2021,2,Monday
1,2,John,HR,SPB,80000.0,32.0,5,15.0,B,2021-03-01,0,92000.0,Low,2021,3,Monday
2,3,Anna,Finance,Kazan,95000.0,29.0,3,NaN,A,2021-04-01,1,NaN,Medium,2021,4,Thursday
3,4,Mike,IT,Moscow,110000.0,41.0,10,20.0,A,2021-05-01,1,132000.0,High,2021,5,Saturday
4,5,Sara,Marketing,SPB,70000.0,24.0,1,5.0,C,2021-06-01,0,73500.0,Low,2021,6,Tuesday

Задание 2
Условие

Создай столбцы:

- hire_year
- hire_month
- hire_day

Использовать
- .dt

Ожидаемый результат

Новые признаки.

Подсказка

.dt.year, .dt.month

In [71]:
em_df['hire_year'] = pd.to_datetime(em_df['employment_date']).dt.year
em_df['hire_month'] = pd.to_datetime(em_df['employment_date']).dt.month
em_df['hire_day'] = pd.to_datetime(em_df['employment_date']).dt.day 

em_df.head()

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote,slary_with_bonus,salary_level,hire_year,hire_month,hire_of_week,hire_day
0,1,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-02-01,1,132000.0,High,2021,2,Monday,1
1,2,John,HR,SPB,80000.0,32.0,5,15.0,B,2021-03-01,0,92000.0,Low,2021,3,Monday,1
2,3,Anna,Finance,Kazan,95000.0,29.0,3,NaN,A,2021-04-01,1,NaN,Medium,2021,4,Thursday,1
3,4,Mike,IT,Moscow,110000.0,41.0,10,20.0,A,2021-05-01,1,132000.0,High,2021,5,Saturday,1
4,5,Sara,Marketing,SPB,70000.0,24.0,1,5.0,C,2021-06-01,0,73500.0,Low,2021,6,Tuesday,1

Задание 3

Условие

Создай столбец:
- day_of_week

Использовать
- .dt.day_name()
Ожидаемый результат

Название дня недели.

Подсказка

Работает только после datetime.

In [73]:
em_df['day_of_week'] = pd.to_datetime(em_df['employment_date']).dt.day_name()
em_df.head()

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote,slary_with_bonus,salary_level,hire_year,hire_month,hire_day,day_of_week
0,1,Alex,IT,Moscow,120000.0,25.0,1,10.0,A,2021-02-01,1,132000.0,High,2021,2,1,Monday
1,2,John,HR,SPB,80000.0,32.0,5,15.0,B,2021-03-01,0,92000.0,Low,2021,3,1,Monday
2,3,Anna,Finance,Kazan,95000.0,29.0,3,NaN,A,2021-04-01,1,NaN,Medium,2021,4,1,Thursday
3,4,Mike,IT,Moscow,110000.0,41.0,10,20.0,A,2021-05-01,1,132000.0,High,2021,5,1,Saturday
4,5,Sara,Marketing,SPB,70000.0,24.0,1,5.0,C,2021-06-01,0,73500.0,Low,2021,6,1,Tuesday

Задание 4
Условие

Выведи сотрудников, нанятых после 2023 года.

Использовать фильтрацию
- .dt.year

Ожидаемый результат

Подтаблица.

Подсказка

Можно фильтровать прямо по .dt.year.

In [74]:
em_df_year = em_df[em_df['hire_year'] == 2023]
em_df_year.head()

,employee_id,name,department,city,salary,age,experience_years,bonus_percent,performance_score,employment_date,remote,slary_with_bonus,salary_level,hire_year,hire_month,hire_day,day_of_week
23,24,Mike,IT,Moscow,110000.0,41.0,10,20.0,A,2023-01-01,1,132000.0,High,2023,1,1,Sunday
24,25,Sara,Marketing,SPB,70000.0,24.0,1,5.0,C,2023-02-01,0,73500.0,Low,2023,2,1,Wednesday
25,26,Tom,Finance,Kazan,99000.0,36.0,7,12.0,B,2023-03-01,0,110880.0,Medium,2023,3,1,Wednesday
26,27,Kate,HR,Moscow,85000.0,28.0,2,8.0,B,2023-04-01,1,91800.0,Low,2023,4,1,Saturday
27,28,Bob,IT,SPB,130000.0,45.0,15,25.0,A,2023-05-01,0,162500.0,High,2023,5,1,Monday

Задание 5
Условие

Преобразуй:

- department
- performance_score

в category.

Использовать
- astype('category')
Ожидаемый результат

Тип category.

Подсказка

Проверь через dtypes.

In [83]:

em_df['department'] = em_df['department'].astype('category')
em_df['performance_score'] = em_df['performance_score'].astype('category')
print(em_df['department'].cat.categories)
print(em_df['performance_score'].cat.categories)
em_df.info()

Index(['Finance', 'HR', 'IT', 'Marketing'], dtype='str')
Index(['A', 'B', 'C'], dtype='str')
<class 'pandas.DataFrame'>
Index: 39 entries, 0 to 39
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        39 non-null     int64
 1   name               39 non-null     str
 2   department         39 non-null     category
 3   city               39 non-null     str
 4   salary             39 non-null     float64
 5   age                38 non-null     float64
 6   experience_years   39 non-null     int64
 7   bonus_percent      32 non-null     float64
 8   performance_score  39 non-null     category
 9   employment_date    39 non-null     datetime64[us]
 10  remote             39 non-null     int64
 11  slary_with_bonus   31 non-null     float64
 12  salary_level       39 non-null     str
 13  hire_year          39 non-null     int32
 14  hire_month         39 non-null     int32
 15  hire_day           39 non-null     int32
 16  day_of_week        39 non-null     str
dtypes: category(2), datetime64[us](1), float64(4), int32(3), int64(3), str(4)
memory usage: 4.5 KB

Задание 6
Условие

Выведи:

список категорий department;
числовые коды категорий.
Использовать
- .cat.categories
- .cat.codes
Ожидаемый результат

Работа с categorical data.

Подсказка

Работает только с category dtype.